//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_SAN_PHAM
    {
        public CHI_TIET_SAN_PHAM()
        {
            this.SAN_PHAM = new HashSet<SAN_PHAM>();
        }
    
        public string HANG_SAN_XUAT { get; set; }
        public string DONG_SAN_PHAM { get; set; }
        public string SO_HIEU_SAN_PHAM { get; set; }
        public string THONG_TIN_KY_THUAT { get; set; }
        public string THONG_TIN_SAN_PHAM { get; set; }
        public Nullable<int> THOI_GIAN_BAO_HANH { get; set; }
        public Nullable<int> CON_TON { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual ICollection<SAN_PHAM> SAN_PHAM { get; set; }
    }
}
