//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        public HOA_DON()
        {
            this.CHI_TIET_HOA_DON = new HashSet<CHI_TIET_HOA_DON>();
        }
    
        public int MA_HOA_DON { get; set; }
        public Nullable<System.DateTime> THOI_GIAN { get; set; }
        public Nullable<int> LOAI_HOA_DON { get; set; }
        public Nullable<int> TONG_CONG { get; set; }
        public string MSNV_THUC_HIEN { get; set; }
        public string THONG_TIN_KHACH_HANG { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual ICollection<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
