//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_SU_NHAN_VIEN
    {
        public string MSNV { get; set; }
        public System.DateTime THOI_GIAN { get; set; }
        public int MA_LICH_SU { get; set; }
        public string MSNV_THUC_HIEN { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN1 { get; set; }
    }
}
