//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUONG
    {
        public string MSNV { get; set; }
        public System.DateTime THOI_GIAN { get; set; }
        public Nullable<int> LUONG_THUONG { get; set; }
        public Nullable<int> TONG_GIO_CONG { get; set; }
        public Nullable<int> HE_SO_LUONG { get; set; }
        public Nullable<int> TONG_LUON { get; set; }
        public Nullable<int> XAC_NHAN_LUONG { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
