//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_QUAN_LY_SHOP_DIEN_THOAIEntities : DbContext
    {
        public DB_QUAN_LY_SHOP_DIEN_THOAIEntities()
            : base("name=DB_QUAN_LY_SHOP_DIEN_THOAIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CA_LAM_VIEC> CA_LAM_VIEC { get; set; }
        public DbSet<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        public DbSet<CHI_TIET_SAN_PHAM> CHI_TIET_SAN_PHAM { get; set; }
        public DbSet<HOA_DON> HOA_DON { get; set; }
        public DbSet<LICH_SU_NHAN_VIEN> LICH_SU_NHAN_VIEN { get; set; }
        public DbSet<LICH_SU_SAN_PHAM> LICH_SU_SAN_PHAM { get; set; }
        public DbSet<LUONG> LUONG { get; set; }
        public DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public DbSet<PHAN_CA> PHAN_CA { get; set; }
        public DbSet<SAN_PHAM> SAN_PHAM { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
