//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN
    {
        public NHAN_VIEN()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
            this.LICH_SU_NHAN_VIEN = new HashSet<LICH_SU_NHAN_VIEN>();
            this.LICH_SU_NHAN_VIEN1 = new HashSet<LICH_SU_NHAN_VIEN>();
            this.LICH_SU_SAN_PHAM = new HashSet<LICH_SU_SAN_PHAM>();
            this.LUONG = new HashSet<LUONG>();
            this.PHAN_CA = new HashSet<PHAN_CA>();
        }
    
        public string MSNV { get; set; }
        public string HO_TEN { get; set; }
        public string CMND { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public string SO_DIEN_THOAI { get; set; }
        public Nullable<int> CHUC_VU { get; set; }
        public string MAT_KHAU { get; set; }
        public Nullable<System.DateTime> NGAY_VAO_LAM { get; set; }
        public Nullable<int> TRANG_THAI { get; set; }
    
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        public virtual ICollection<LICH_SU_NHAN_VIEN> LICH_SU_NHAN_VIEN { get; set; }
        public virtual ICollection<LICH_SU_NHAN_VIEN> LICH_SU_NHAN_VIEN1 { get; set; }
        public virtual ICollection<LICH_SU_SAN_PHAM> LICH_SU_SAN_PHAM { get; set; }
        public virtual ICollection<LUONG> LUONG { get; set; }
        public virtual ICollection<PHAN_CA> PHAN_CA { get; set; }
    }
}
