//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHAN_CA
    {
        public string MSNV { get; set; }
        public System.DateTime THOI_GIAN { get; set; }
        public Nullable<int> CA { get; set; }
        public Nullable<int> CHAM_CONG { get; set; }
        public Nullable<int> XAC_NHAN_CONG { get; set; }
    
        public virtual CA_LAM_VIEC CA_LAM_VIEC { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
