//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        public SAN_PHAM()
        {
            this.CHI_TIET_HOA_DON = new HashSet<CHI_TIET_HOA_DON>();
            this.LICH_SU_SAN_PHAM = new HashSet<LICH_SU_SAN_PHAM>();
        }
    
        public string IMEI { get; set; }
        public string HANG_SAN_XUAT { get; set; }
        public string DONG_SAN_PHAM { get; set; }
        public string SO_HIEU_SAN_PHAM { get; set; }
        public string TEN_SAN_PHAM { get; set; }
        public Nullable<System.DateTime> NGAY_BAT_DAU_BAO_HANH { get; set; }
        public Nullable<System.DateTime> NGAY_KET_THUC_BAO_HANG { get; set; }
        public int TRANG_THAI { get; set; }
        public string GHI_CHU { get; set; }
        public int GIA_MUA { get; set; }
        public int GIA_BAN { get; set; }
    
        public virtual ICollection<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        public virtual CHI_TIET_SAN_PHAM CHI_TIET_SAN_PHAM { get; set; }
        public virtual ICollection<LICH_SU_SAN_PHAM> LICH_SU_SAN_PHAM { get; set; }
    }
}
