//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_LAM_VIEC
    {
        public CA_LAM_VIEC()
        {
            this.PHAN_CA = new HashSet<PHAN_CA>();
        }
    
        public int CA { get; set; }
        public Nullable<int> GIO { get; set; }
    
        public virtual ICollection<PHAN_CA> PHAN_CA { get; set; }
    }
}
