CREATE database DB_QUAN_LY_SHOP_DIEN_THOAI;
go

use DB_QUAN_LY_SHOP_DIEN_THOAI;

CREATE TABLE HANG_SAN_XUAT
(
	MA_HANG INT PRIMARY KEY IDENTITY(1,1),
	HANG NVARCHAR(50) NOT NULL
)

create table CHI_TIET_SAN_PHAM
(
	MA_CHI_TIET_SAN_PHAM INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	MA_HANG INT NOT NULL,
	DONG_SAN_PHAM NVARCHAR(50),
	SO_HIEU_SAN_PHAM NVARCHAR(50),
	TEN_SAN_PHAM NVARCHAR(200) NOT NULL,
	THONG_TIN_KY_THUAT TEXT,
	THONG_TIN_SAN_PHAM TEXT,
	THOI_GIAN_BAO_HANH INT,
	GHI_CHU TEXT,
	GIA_BAN INT NOT NULL
)

create table SAN_PHAM
(
	IMEI NVARCHAR(20),
	MA_KHO INT NOT NULL,
	MA_CHI_TIET_SAN_PHAM INT NOT NULL,
	NGAY_BAT_DAU_BAO_HANH DATETIME,
	NGAY_KET_THUC_BAO_HANH DATETIME,
	TRANG_THAI INT NOT NULL,
	GHI_CHU TEXT,
	GIA_MUA INT,
	GIA_BAN INT,
	PRIMARY KEY(IMEI)
)

CREATE TABLE LICH_SU_SAN_PHAM
(
	IMEI NVARCHAR(20),
	THOI_GIAN DATETIME,
	MA_LICH_SU INT,
	MSNV_THUC_HIEN INT,
	GHI_CHU TEXT,
	PRIMARY KEY (IMEI, THOI_GIAN, MA_LICH_SU)
)

CREATE TABLE NHAN_VIEN
(
	MSNV INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	HO_TEN TEXT,
	CMND TEXT,
	NGAY_SINH DATETIME,
	SO_DIEN_THOAI TEXT,
	CHUC_VU INT,
	MAT_KHAU TEXT,
	NGAY_VAO_LAM DATETIME,
	TRANG_THAI INT
)

CREATE TABLE LICH_SU_NHAN_VIEN
(
	MSNV INT,
	THOI_GIAN DATETIME,
	MA_LICH_SU INT,
	MSNV_THUC_HIEN INT,
	GHI_CHU TEXT,
	PRIMARY KEY (MSNV, THOI_GIAN, MA_LICH_SU)
)

CREATE TABLE LUONG
(
	MSNV INT,
	THOI_GIAN DATETIME,
	LUONG_THUONG INT,
	TONG_GIO_CONG INT,
	HE_SO_LUONG INT,
	TONG_LUONG INT,
	XAC_NHAN_LUONG INT,
	PRIMARY KEY (MSNV, THOI_GIAN)
)

CREATE TABLE PHAN_CA
(
	MSNV INT,
	THOI_GIAN DATETIME,
	CA INT,
	CHAM_CONG INT NOT NULL,
	XAC_NHAN_CONG INT NOT NULL,
	PRIMARY KEY (MSNV, THOI_GIAN, CA)
)

CREATE TABLE CA_LAM_VIEC
(
	CA INT,
	GIO INT NOT NULL,
	BAT_DAU TIME(7),
	KET_THUC TIME(7),
	PRIMARY KEY (CA)
)

CREATE TABLE HOA_DON
(
	MA_HOA_DON INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	THOI_GIAN DATETIME,
	LOAI_HOA_DON INT,
	TONG_CONG INT,
	MSNV_THUC_HIEN INT,
	THONG_TIN_KHACH_HANG TEXT,
	MA_DOI_TAC INT,
	GHI_CHU TEXT
)

CREATE TABLE CHI_TIET_HOA_DON
(
	MA_HOA_DON INT,
	IMEI NVARCHAR(20),
	GIA INT,
	GHI_CHU TEXT,
	PRIMARY KEY (MA_HOA_DON, IMEI)
)

CREATE TABLE DOI_TAC_NHAP_HANG
(
	MA_DOI_TAC INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	THONG_TIN TEXT,
	SO_DIEN_THOAI TEXT,
	MSNV_QUAN_LY INT
)

CREATE TABLE CHUC_VU_NHAN_VIEN
(
	MA_CHUC_VU INT NOT NULL PRIMARY KEY,
	CHUC_VU TEXT
)

CREATE TABLE KHO_HANG
(
	MA_KHO INT IDENTITY(1,1) PRIMARY KEY,
	MA_DOI_TAC int not null,
	MA_CHI_TIET_SAN_PHAM INT NOT NULL,
	THOI_GIAN DATETIME NOT NULL,
	GIA_MUA INT NOT NULL,
	SO_LUONG INT NOT NULL,
	CON_LAI INT NOT NULL,
	MSNV_THUC_HIEN INT
)

CREATE table TRANG_THAI_SAN_PHAM
(
	MA_TRANG_THAI int IDENTITY(0,1) PRIMARY KEY,
	TRANG_THAI text not null
)

ALTER TABLE SAN_PHAM
ADD CONSTRAINT FK_SAN_PHAM_TRANG_THAI_SAN_PHAM
FOREIGN KEY (TRANG_THAI)
REFERENCES TRANG_THAI_SAN_PHAM(MA_TRANG_THAI)

ALTER TABLE SAN_PHAM
ADD CONSTRAINT FK_SAN_PHAM_KHO_HANG
FOREIGN KEY (MA_KHO)
REFERENCES KHO_HANG(MA_KHO)

ALTER TABLE KHO_HANG
ADD CONSTRAINT FK_KHO_HANG_CHI_TIET_SAN_PHAM
FOREIGN KEY (MA_CHI_TIET_SAN_PHAM)
REFERENCES CHI_TIET_SAN_PHAM(MA_CHI_TIET_SAN_PHAM)

ALTER TABLE KHO_HANG
ADD CONSTRAINT FK_KHO_HANG_DOI_TAC_NHAP_HANG
FOREIGN KEY (MA_DOI_TAC)
REFERENCES DOI_TAC_NHAP_HANG(MA_DOI_TAC)


ALTER TABLE LICH_SU_SAN_PHAM
ADD CONSTRAINT FK_LICH_SU_SAN_PHAM_SAN_PHAM
FOREIGN KEY (IMEI)
REFERENCES SAN_PHAM(IMEI)

ALTER TABLE LICH_SU_SAN_PHAM
ADD CONSTRAINT FK_LICH_SU_SAN_PHAM_NHAN_VIEN
FOREIGN KEY (MSNV_THUC_HIEN)
REFERENCES NHAN_VIEN(MSNV)

ALTER TABLE SAN_PHAM
ADD CONSTRAINT FK_SAN_PHAM_CHI_TIET_SAN_PHAM
FOREIGN KEY (MA_CHI_TIET_SAN_PHAM)
REFERENCES CHI_TIET_SAN_PHAM(MA_CHI_TIET_SAN_PHAM)

ALTER TABLE LICH_SU_NHAN_VIEN
ADD CONSTRAINT FK_LICH_SU_NHAN_VIEN_NHAN_VIEN
FOREIGN KEY (MSNV)
REFERENCES NHAN_VIEN(MSNV)

ALTER TABLE LICH_SU_NHAN_VIEN
ADD CONSTRAINT FK_LICH_SU_NHAN_VIEN_NHAN_VIEN_1
FOREIGN KEY (MSNV_THUC_HIEN)
REFERENCES NHAN_VIEN(MSNV)

ALTER TABLE LUONG
ADD CONSTRAINT FK_LUONG_NHAN_VIEN
FOREIGN KEY (MSNV)
REFERENCES NHAN_VIEN(MSNV)

ALTER TABLE PHAN_CA
ADD CONSTRAINT FK_PHAN_CA_NHAN_VIEN
FOREIGN KEY (MSNV)
REFERENCES NHAN_VIEN(MSNV)

ALTER TABLE PHAN_CA
ADD CONSTRAINT FK_PHAN_CA_CA_LAM_VIEC
FOREIGN KEY (CA)
REFERENCES CA_LAM_VIEC(CA)

ALTER TABLE HOA_DON
ADD CONSTRAINT FK_HOA_DON_NHAN_VIEN
FOREIGN KEY (MSNV_THUC_HIEN)
REFERENCES NHAN_VIEN(MSNV)

ALTER TABLE CHI_TIET_HOA_DON
ADD CONSTRAINT FK_CHI_TIET_HOA_DON_HOA_DON
FOREIGN KEY (MA_HOA_DON)
REFERENCES HOA_DON(MA_HOA_DON)

ALTER TABLE CHI_TIET_HOA_DON
ADD CONSTRAINT FK_CHI_TIET_HOA_DON_SAN_PHAM
FOREIGN KEY (IMEI)
REFERENCES SAN_PHAM(IMEI)

ALTER TABLE DOI_TAC_NHAP_HANG
ADD CONSTRAINT FK_DOI_TAC_NHAP_HANG_NHAN_VIEN
FOREIGN KEY (MSNV_QUAN_LY)
REFERENCES NHAN_VIEN(MSNV)

ALTER TABLE HOA_DON
ADD CONSTRAINT FK_HOA_DON_DOI_TAC_NHAP_HANG
FOREIGN KEY (MA_DOI_TAC)
REFERENCES DOI_TAC_NHAP_HANG(MA_DOI_TAC)

ALTER TABLE CHI_TIET_SAN_PHAM
ADD CONSTRAINT FK_CHI_TIET_SAN_PHAM_HANG_SAN_XUAT
FOREIGN KEY (MA_HANG)
REFERENCES HANG_SAN_XUAT(MA_HANG)